//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TATconexionSAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEXTOCARTAV
    {
        public string SPRAS_ID { get; set; }
        public string E_MAIL { get; set; }
        public string ESTIMADO { get; set; }
        public string CONTROL { get; set; }
        public string DE { get; set; }
        public string A { get; set; }
        public string MATERIAL { get; set; }
        public string CATEGORIA { get; set; }
        public string DESCRIPCION { get; set; }
        public string COSTOU { get; set; }
        public string APOYOP { get; set; }
        public string APOYOPP { get; set; }
        public string COSTOA { get; set; }
        public string PRECIOSU { get; set; }
        public string FOLIO { get; set; }
        public string PAYER { get; set; }
        public string MONTO { get; set; }
        public string MARCA_AGUA { get; set; }
        public string APOYOEST { get; set; }
        public string APOYOREA { get; set; }
    }
}
