//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TATconexionSAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEXTOCARTAF
    {
        public string SPRAS_ID { get; set; }
        public string E_MAIL { get; set; }
        public string ESTIMADO { get; set; }
        public string CONTROL { get; set; }
        public string FOLIO { get; set; }
        public string PAYER { get; set; }
        public string MONTO { get; set; }
        public string MARCA_AGUA { get; set; }
    }
}
